name: CI
on:
  pull_request:
  push:
    branches: [rts/isometric-conversion]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm --include=dev ci
      - run: npm --include=dev run typecheck
      - run: npm --include=dev run build
      - run: npm --include=dev test
